version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
        text: "G404"
